
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler - derived identifiers and metadata describing       *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include "../reg_ids.h"
#include "../reg_decls.h"
#include "Date.h"


namespace regs0::fn {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().function<nsdate::Date>(cxx::fn::nsdate::getDateAsString::id)
                                 .build(&nsdate::getDateAsString));

        fns.push_back(rtl::type().function<unsigned int, unsigned int, unsigned int>(cxx::fn::nsdate::getDateAsString::id)
                                 .build(&nsdate::getDateAsString));
    }
}


namespace regs0::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<nsdate::Date>(cxx::type::nsdate::Date::id)
                                 .build());

        fns.push_back(rtl::type().member<nsdate::Date>()
                                 .method(cxx::type::nsdate::Date::fn::set::id)
                                 .build(&nsdate::Date::set));
    }
}

