#pragma once

#include <string>
#include <chrono>
#include <string_view>
#include <unordered_map>

namespace clmr
{
	namespace color 
	{
		inline constexpr std::string_view RESET = "\033[0m";
		inline constexpr std::string_view DARK_RED = "\033[31m";
		inline constexpr std::string_view RED = "\033[38;2;231;72;86m";
		inline constexpr std::string_view GREEN = "\033[32m";
		inline constexpr std::string_view YELLOW = "\033[33m";
		inline constexpr std::string_view BLUE = "\033[34m";
		inline constexpr std::string_view MAGENTA = "\033[35m";
		inline constexpr std::string_view CYAN = "\033[38;2;97;214;214m";
		inline constexpr std::string_view WHITE = "\033[37m";
		inline constexpr std::string_view TEAL = "\033[38;2;0;128;128m";
		inline constexpr std::string_view GREY = "\033[38;2;118;118;118m";
	}

	inline constexpr std::size_t index_none = std::size_t(-1);

	inline constexpr std::string_view CONST = "const";
	inline constexpr std::string_view ENUM = "enum";
	inline constexpr std::string_view CLASS = "class";
	inline constexpr std::string_view STRUCT = "struct";
	

	inline constexpr std::string_view VAR_ID = "id";
	inline constexpr std::string_view NS_CXX = "cxx";
	inline constexpr std::string_view NS_RTL = "rtl";
	inline constexpr std::string_view NS_TYPE = "type";
	inline constexpr std::string_view NS_FN = "fn";
	inline constexpr std::string_view NS_REGS = "regs";
	
	inline constexpr std::string_view REGIS_FN_INIT = "init";
	inline constexpr std::string_view REGIS_INIT_DECL = "void init(std::vector<rtl::Function>&)";	 // function name should be same as in REGIS_FN_INIT.
	inline constexpr std::string_view REGIS_INIT_DEFN = "void init(std::vector<rtl::Function>& fns)"; // function name should be same as in REGIS_FN_INIT.
}


namespace clmr 
{
	enum MetaKind 
	{
		None,
		Ctor,
		NonMemberFn,
		MemberFnConst,
		MemberFnStatic,
		MemberFnNonConst
	};

	struct File 
	{
		static constexpr std::string_view dirSrc = "reg_src";
		static constexpr std::string_view dirRoot = "RTLRegistration";
		static constexpr std::string_view prefixRegs = "regs";
		static constexpr std::string_view nameIDsHeader = "reg_ids.h";
		static constexpr std::string_view nameRegHeader = "reg_decls.h";
		static constexpr std::string_view nameCxxHeader = "cxx_mirror.h";
		static constexpr std::string_view nameCxxSource = "cxx_mirror.cpp";
		static constexpr std::string_view incRtlAccess = "rtl_access.h";
		static constexpr std::string_view incRtlBuilder = "rtl_builder.h";
	};

	struct ASTRecordMeta;
	struct ASTCodeMeta;

	using CxxRecordsMap = std::unordered_map<std::string, ASTRecordMeta>;
	using CxxFunctionsMap = std::unordered_map<std::string, ASTCodeMeta>;

	using Clock = std::chrono::high_resolution_clock;
	using Second = std::chrono::duration<double, std::ratio<1> >;
}



#define GETTER_REF(_varType, _name, _var)       \
    inline constexpr _varType& get##_name() {   \
        return _var;                            \
    }

#define GETTER_CREF(_varType, _name, _var)                 \
    inline constexpr const _varType& get##_name() const {  \
        return _var;                                       \
    }

#define GETTER_BOOL(_name, _var)                        \
    inline constexpr const bool is##_name() const {     \
        return _var;                                    \
    }


namespace clmr 
{
	inline constexpr std::string_view CLANG_MIRROR_GENERATED_HEADER_TEXT =
		"\n/*****************************************************************************\n"
		  " *                                                                           *\n"
		  " *  `clang-mirror` generated file.                                           *\n"
		  " *                                                                           *\n"
		  " *  This file is automatically generated by `clang-mirror` and represents    *\n"
		  " *  the reflected projection of user code for consumption by the             *\n"
		  " *  Reflection Template Library(RTL).                                        *\n"
		  " *                                                                           *\n"
		  " *  It contains compiler-derived identifiers and metadata describing         *\n"
		  " *  namespaces, types, and members selected for reflection.                  *\n"
		  " *                                                                           *\n"
		  " *  DO NOT EDIT THIS FILE MANUALLY.                                          *\n"
		  " *  Any changes will be overwritten by the generator.                        *\n"
		  " *                                                                           *\n"
		  " *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *\n"
		  " *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *\n"
		  " *                                                                           *\n"
		  " *****************************************************************************/\n";
}