
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler - derived identifiers and metadata describing       *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <vector>

#include "../reg_decls.h"

namespace cxx { 

    const rtl::CxxMirror& mirror()
    {
        static auto mirror = rtl::CxxMirror([]() {

            std::vector<rtl::Function> fns;

            regs9::fn::init(fns);
            regs2::fn::init(fns);
            regs11::type0::init(fns);
            regs11::type1::init(fns);
            regs11::type2::init(fns);
            regs11::type3::init(fns);
            regs11::type4::init(fns);
            regs10::type0::init(fns);
            regs8::type0::init(fns);
            regs6::type0::init(fns);
            regs5::type0::init(fns);
            regs4::type0::init(fns);
            regs7::type0::init(fns);
            regs1::type0::init(fns);
            regs3::type0::init(fns);
            regs3::type1::init(fns);
            regs3::type2::init(fns);
            regs0::type0::init(fns);
            return fns;
        }());
        return mirror;
    }
}