name: windows-release-build

on:
  push:
    branches:
      - release
  workflow_dispatch:

concurrency:
  group: release-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    env:
      LLVM_VERSION: 21.1.0
      LLVM_DIR_NAME: clang+llvm-21.1.0-x86_64-pc-windows-msvc
      REL: release-latest

    steps:

      # ----------------------------
      # Checkout
      # ----------------------------
      - uses: actions/checkout@v4

      # ----------------------------
      # Download LLVM
      # ----------------------------
      - name: Download LLVM
        shell: pwsh
        run: |
          curl -L -o llvm.tar.xz `
            https://github.com/llvm/llvm-project/releases/download/llvmorg-${env:LLVM_VERSION}/${env:LLVM_DIR_NAME}.tar.xz

      - name: Extract LLVM
        shell: pwsh
        run: |
          tar -xf llvm.tar.xz
          Rename-Item "${env:LLVM_DIR_NAME}" llvm

      # ----------------------------
      # Configure
      # ----------------------------
      - name: Configure
        shell: pwsh
        run: |
          cmake -S . -B build `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DLLVM_ROOT="$pwd/llvm"

      # ----------------------------
      # Build
      # ----------------------------
      - name: Build
        shell: pwsh
        run: |
          cmake --build build --config Release --parallel

      # ----------------------------
      # Package
      # ----------------------------
      - name: Package
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path release | Out-Null
          Copy-Item bin/Release/clang-mirror.exe release/
          Compress-Archive release clang-mirror-windows.zip -Force

      # ----------------------------
      # Upload asset (Release created by Linux workflow)
      # ----------------------------
      - name: Upload asset
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $env:REL `
            clang-mirror-windows.zip `
            --clobber
